// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testAPIKeys(t *testing.T) {
	t.Parallel()

	query := APIKeys()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testAPIKeysDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &APIKey{}
	if err = randomize.Struct(seed, o, apiKeyDBTypes, true, apiKeyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize APIKey struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := APIKeys().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAPIKeysQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &APIKey{}
	if err = randomize.Struct(seed, o, apiKeyDBTypes, true, apiKeyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize APIKey struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := APIKeys().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := APIKeys().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAPIKeysSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &APIKey{}
	if err = randomize.Struct(seed, o, apiKeyDBTypes, true, apiKeyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize APIKey struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := APIKeySlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := APIKeys().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAPIKeysExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &APIKey{}
	if err = randomize.Struct(seed, o, apiKeyDBTypes, true, apiKeyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize APIKey struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := APIKeyExists(ctx, tx, o.KeyID)
	if err != nil {
		t.Errorf("Unable to check if APIKey exists: %s", err)
	}
	if !e {
		t.Errorf("Expected APIKeyExists to return true, but got false.")
	}
}

func testAPIKeysFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &APIKey{}
	if err = randomize.Struct(seed, o, apiKeyDBTypes, true, apiKeyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize APIKey struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	apiKeyFound, err := FindAPIKey(ctx, tx, o.KeyID)
	if err != nil {
		t.Error(err)
	}

	if apiKeyFound == nil {
		t.Error("want a record, got nil")
	}
}

func testAPIKeysBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &APIKey{}
	if err = randomize.Struct(seed, o, apiKeyDBTypes, true, apiKeyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize APIKey struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = APIKeys().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testAPIKeysOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &APIKey{}
	if err = randomize.Struct(seed, o, apiKeyDBTypes, true, apiKeyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize APIKey struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := APIKeys().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testAPIKeysAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	apiKeyOne := &APIKey{}
	apiKeyTwo := &APIKey{}
	if err = randomize.Struct(seed, apiKeyOne, apiKeyDBTypes, false, apiKeyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize APIKey struct: %s", err)
	}
	if err = randomize.Struct(seed, apiKeyTwo, apiKeyDBTypes, false, apiKeyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize APIKey struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = apiKeyOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = apiKeyTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := APIKeys().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testAPIKeysCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	apiKeyOne := &APIKey{}
	apiKeyTwo := &APIKey{}
	if err = randomize.Struct(seed, apiKeyOne, apiKeyDBTypes, false, apiKeyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize APIKey struct: %s", err)
	}
	if err = randomize.Struct(seed, apiKeyTwo, apiKeyDBTypes, false, apiKeyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize APIKey struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = apiKeyOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = apiKeyTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := APIKeys().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func apiKeyBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *APIKey) error {
	*o = APIKey{}
	return nil
}

func apiKeyAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *APIKey) error {
	*o = APIKey{}
	return nil
}

func apiKeyAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *APIKey) error {
	*o = APIKey{}
	return nil
}

func apiKeyBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *APIKey) error {
	*o = APIKey{}
	return nil
}

func apiKeyAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *APIKey) error {
	*o = APIKey{}
	return nil
}

func apiKeyBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *APIKey) error {
	*o = APIKey{}
	return nil
}

func apiKeyAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *APIKey) error {
	*o = APIKey{}
	return nil
}

func apiKeyBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *APIKey) error {
	*o = APIKey{}
	return nil
}

func apiKeyAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *APIKey) error {
	*o = APIKey{}
	return nil
}

func testAPIKeysHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &APIKey{}
	o := &APIKey{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, apiKeyDBTypes, false); err != nil {
		t.Errorf("Unable to randomize APIKey object: %s", err)
	}

	AddAPIKeyHook(boil.BeforeInsertHook, apiKeyBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	apiKeyBeforeInsertHooks = []APIKeyHook{}

	AddAPIKeyHook(boil.AfterInsertHook, apiKeyAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	apiKeyAfterInsertHooks = []APIKeyHook{}

	AddAPIKeyHook(boil.AfterSelectHook, apiKeyAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	apiKeyAfterSelectHooks = []APIKeyHook{}

	AddAPIKeyHook(boil.BeforeUpdateHook, apiKeyBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	apiKeyBeforeUpdateHooks = []APIKeyHook{}

	AddAPIKeyHook(boil.AfterUpdateHook, apiKeyAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	apiKeyAfterUpdateHooks = []APIKeyHook{}

	AddAPIKeyHook(boil.BeforeDeleteHook, apiKeyBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	apiKeyBeforeDeleteHooks = []APIKeyHook{}

	AddAPIKeyHook(boil.AfterDeleteHook, apiKeyAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	apiKeyAfterDeleteHooks = []APIKeyHook{}

	AddAPIKeyHook(boil.BeforeUpsertHook, apiKeyBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	apiKeyBeforeUpsertHooks = []APIKeyHook{}

	AddAPIKeyHook(boil.AfterUpsertHook, apiKeyAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	apiKeyAfterUpsertHooks = []APIKeyHook{}
}

func testAPIKeysInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &APIKey{}
	if err = randomize.Struct(seed, o, apiKeyDBTypes, true, apiKeyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize APIKey struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := APIKeys().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testAPIKeysInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &APIKey{}
	if err = randomize.Struct(seed, o, apiKeyDBTypes, true); err != nil {
		t.Errorf("Unable to randomize APIKey struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(apiKeyColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := APIKeys().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testAPIKeysReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &APIKey{}
	if err = randomize.Struct(seed, o, apiKeyDBTypes, true, apiKeyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize APIKey struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testAPIKeysReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &APIKey{}
	if err = randomize.Struct(seed, o, apiKeyDBTypes, true, apiKeyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize APIKey struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := APIKeySlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testAPIKeysSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &APIKey{}
	if err = randomize.Struct(seed, o, apiKeyDBTypes, true, apiKeyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize APIKey struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := APIKeys().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	apiKeyDBTypes = map[string]string{`KeyID`: `integer`, `KeyVal`: `character varying`}
	_             = bytes.MinRead
)

func testAPIKeysUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(apiKeyPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(apiKeyAllColumns) == len(apiKeyPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &APIKey{}
	if err = randomize.Struct(seed, o, apiKeyDBTypes, true, apiKeyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize APIKey struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := APIKeys().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, apiKeyDBTypes, true, apiKeyPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize APIKey struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testAPIKeysSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(apiKeyAllColumns) == len(apiKeyPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &APIKey{}
	if err = randomize.Struct(seed, o, apiKeyDBTypes, true, apiKeyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize APIKey struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := APIKeys().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, apiKeyDBTypes, true, apiKeyPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize APIKey struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(apiKeyAllColumns, apiKeyPrimaryKeyColumns) {
		fields = apiKeyAllColumns
	} else {
		fields = strmangle.SetComplement(
			apiKeyAllColumns,
			apiKeyPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := APIKeySlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testAPIKeysUpsert(t *testing.T) {
	t.Parallel()

	if len(apiKeyAllColumns) == len(apiKeyPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := APIKey{}
	if err = randomize.Struct(seed, &o, apiKeyDBTypes, true); err != nil {
		t.Errorf("Unable to randomize APIKey struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert APIKey: %s", err)
	}

	count, err := APIKeys().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, apiKeyDBTypes, false, apiKeyPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize APIKey struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert APIKey: %s", err)
	}

	count, err = APIKeys().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
