// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Formations       string
	Groups           string
	MemberInfos      string
	MemberTags       string
	Members          string
	SchemaMigrations string
	Tags             string
}{
	Formations:       "formations",
	Groups:           "groups",
	MemberInfos:      "member_infos",
	MemberTags:       "member_tags",
	Members:          "members",
	SchemaMigrations: "schema_migrations",
	Tags:             "tags",
}
