// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	APIKeys          string
	Blogs            string
	Formations       string
	Groups           string
	MemberInfos      string
	MemberTags       string
	Members          string
	Positions        string
	SchemaMigrations string
	Songs            string
	Tags             string
}{
	APIKeys:          "api_keys",
	Blogs:            "blogs",
	Formations:       "formations",
	Groups:           "groups",
	MemberInfos:      "member_infos",
	MemberTags:       "member_tags",
	Members:          "members",
	Positions:        "positions",
	SchemaMigrations: "schema_migrations",
	Songs:            "songs",
	Tags:             "tags",
}
