// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Formations", testFormationsUpsert)

	t.Run("Groups", testGroupsUpsert)

	t.Run("MemberInfos", testMemberInfosUpsert)

	t.Run("MemberTags", testMemberTagsUpsert)

	t.Run("Members", testMembersUpsert)

	t.Run("SchemaMigrations", testSchemaMigrationsUpsert)

	t.Run("Tags", testTagsUpsert)
}
