DROP TABLE IF EXISTS member_infos;
DROP TABLE IF EXISTS member_tags;
DROP TABLE IF EXISTS positions;
DROP TABLE IF EXISTS songs;
DROP TABLE IF EXISTS members;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS groups;
DROP TABLE IF EXISTS formations;
