output   = "my_models"
wipe     = true
no-tests = false

[psql]
  dbname = "sakamichi"
  host   = "localhost"
  port   = 5432
  user   = "ubuntu"
  pass   = "sakamichi"
  sslmode= "disable"
  blacklist = []
